import type { Card } from "./card.js";

function card(name: string, typeLine: string, oracleText: string, extra: Partial<Card> = {}): Card {
  return { name, typeLine, oracleText, keywords: [], colors: [], manaValue: 0, ...extra };
}

export const FIXTURES: Record<string, Card> = {
  dockside: card(
    "Dockside Extortionist",
    "Legendary Creature — Goblin Pirate",
    "When Dockside Extortionist enters the battlefield, create a number of Treasure tokens equal to the number of artifacts and enchantments your opponents control.",
    { colors: ["R"], manaValue: 2 },
  ),
  fireweaver: card(
    "Reckless Fireweaver",
    "Creature — Human Artificer",
    "Whenever an artifact enters the battlefield under your control, Reckless Fireweaver deals 1 damage to each opponent.",
    { colors: ["R"], manaValue: 2 },
  ),
  krenko: card(
    "Krenko, Mob Boss",
    "Legendary Creature — Goblin Warrior",
    "Tap: Create a number of 1/1 red Goblin creature tokens equal to the number of Goblins you control.",
    { colors: ["R"], manaValue: 4 },
  ),
  impactTremors: card(
    "Impact Tremors",
    "Enchantment",
    "Whenever a creature enters the battlefield under your control, Impact Tremors deals 1 damage to each opponent.",
    { colors: ["R"], manaValue: 2 },
  ),
  ashnods: card(
    "Ashnod's Altar",
    "Artifact",
    "Sacrifice a creature: Add two colorless mana.",
    { manaValue: 3 },
  ),
  bloodArtist: card(
    "Blood Artist",
    "Creature — Vampire",
    "Whenever Blood Artist or another creature dies, target player loses 1 life and you gain 1 life.",
    { colors: ["B"], manaValue: 2 },
  ),
  cultivate: card(
    "Cultivate",
    "Sorcery",
    "Search your library for up to two basic land cards, reveal them, put one onto the battlefield tapped and the other into your hand, then shuffle.",
    { colors: ["G"], manaValue: 3 },
  ),
  lotusCobra: card(
    "Lotus Cobra",
    "Creature — Snake",
    "Landfall — Whenever a land enters the battlefield under your control, add one mana of any color.",
    { colors: ["G"], manaValue: 2 },
  ),
  swordsToPlowshares: card(
    "Swords to Plowshares",
    "Instant",
    "Exile target creature. Its controller gains life equal to its power.",
    { colors: ["W"], manaValue: 1 },
  ),
  divination: card(
    "Divination",
    "Sorcery",
    "Draw two cards.",
    { colors: ["U"], manaValue: 3 },
  ),
  // Combo pieces
  thassasOracle: card(
    "Thassa's Oracle",
    "Creature — Merfolk Wizard",
    "When Thassa's Oracle enters the battlefield, look at the top X cards of your library, where X is your devotion to blue. If your library and hand contain X or fewer cards, you win the game.",
    { colors: ["U"], manaValue: 2 },
  ),
  consultation: card(
    "Demonic Consultation",
    "Instant",
    "Name a card. Exile the top six cards of your library, then exile all cards with that name from your library. Put the rest into your hand.",
    { colors: ["B"], manaValue: 1 },
  ),
  goblinChieftain: card(
    "Goblin Chieftain",
    "Creature — Goblin",
    "Other Goblin creatures you control get +1/+1 and have haste.",
    { colors: ["R"], manaValue: 3 },
  ),
  goblinRecruiter: card(
    "Goblin Recruiter",
    "Creature — Goblin",
    "When Goblin Recruiter enters the battlefield, search your library for any number of Goblin cards.",
    { colors: ["R"], manaValue: 3 },
  ),
  lightningBolt: card(
    "Lightning Bolt",
    "Instant",
    "Lightning Bolt deals 3 damage to any target.",
    { colors: ["R"], manaValue: 1 },
  ),
  archmageEmeritus: card(
    "Archmage Emeritus",
    "Creature — Human Wizard",
    "Magecraft — Whenever you cast or copy an instant or sorcery spell, draw a card.",
    { colors: ["U"], manaValue: 4 },
  ),
  guardianOfFaith: card(
    "Guardian of Faith",
    "Creature — Spirit Cleric",
    "Creatures you control can't be sacrificed.",
    { colors: ["W"], manaValue: 3 },
  ),
  sacImmunity: card(
    "Sacrosanct Ward",
    "Enchantment",
    "Players can't sacrifice a creature.",
    {},
  ),
  stitchersSupplier: card(
    "Stitcher's Supplier",
    "Creature — Zombie",
    "When Stitcher's Supplier enters the battlefield or dies, mill three cards.",
    { colors: ["B"], manaValue: 1 },
  ),
  gravedigger: card(
    "Gravedigger",
    "Creature — Zombie",
    "When Gravedigger enters the battlefield, return target creature card from your graveyard to your hand.",
    { colors: ["B"], manaValue: 4 },
  ),
  soulWarden: card(
    "Soul Warden",
    "Creature — Human Cleric",
    "Whenever another creature enters the battlefield, you gain 1 life.",
    { colors: ["W"], manaValue: 1 },
  ),
  archangelOfThune: card(
    "Archangel of Thune",
    "Creature — Angel",
    "Whenever you gain life, put a +1/+1 counter on each creature you control.",
    { colors: ["W"], manaValue: 5, keywords: ["Flying", "Lifelink"] },
  ),
  ephemerate: card(
    "Ephemerate",
    "Instant",
    "Exile target creature you control, then return it to the battlefield under its owner's control.",
    { colors: ["W"], manaValue: 1 },
  ),
  mulldrifter: card(
    "Mulldrifter",
    "Creature — Elemental",
    "When Mulldrifter enters the battlefield, draw two cards.",
    { colors: ["U"], manaValue: 5, keywords: ["Flying"] },
  ),
  decoyTokenMaker: card(
    "Decoy Rally",
    "Sorcery",
    "Create three 1/1 white creature tokens. When an Elf enters the battlefield, draw a card.",
    { colors: ["W"], manaValue: 4 },
  ),
  wizardTokenMaker: card(
    "Wizard Standard",
    "Enchantment",
    "At the beginning of your upkeep, create a 1/1 blue Wizard creature token.",
    { colors: ["U"], manaValue: 3 },
  ),
  wildGrowth: card(
    "Wild Growth",
    "Enchantment — Aura",
    "Enchant land. Whenever enchanted land is tapped for mana, its controller adds an additional {G}.",
    { colors: ["G"], manaValue: 1 },
  ),
  enchantressPresence: card(
    "Enchantress's Presence",
    "Enchantment",
    "Whenever you cast an enchantment spell, draw a card.",
    { colors: ["G"], manaValue: 3 },
  ),
  bonesplitter: card(
    "Bonesplitter",
    "Artifact — Equipment",
    "Equipped creature gets +2/+0. Equip {1}.",
    { manaValue: 1 },
  ),
  puresteelPaladin: card(
    "Puresteel Paladin",
    "Creature — Human Soldier",
    "Whenever an Equipment you control becomes attached to a creature, draw a card. Metalcraft — Equipment you control have equip {0} as long as you control three or more artifacts.",
    { colors: ["W"], manaValue: 2 },
  ),
  arcboundRavager: card(
    "Arcbound Ravager",
    "Artifact Creature — Beast",
    "Sacrifice an artifact: Put a +1/+1 counter on Arcbound Ravager.",
    { manaValue: 2, keywords: ["Modular"] },
  ),
  evolutionSage: card(
    "Evolution Sage",
    "Creature — Elf Druid",
    "Landfall — Whenever a land enters the battlefield under your control, proliferate.",
    { colors: ["G"], manaValue: 4 },
  ),
  isshin: card(
    "Isshin, Two Heavens as One",
    "Legendary Creature — Human Samurai",
    "Double strike. If a creature entering the battlefield or attacking causes a triggered ability of a permanent you control to trigger, that ability triggers an additional time.",
    { colors: ["R", "W", "B"], manaValue: 3, keywords: ["Double strike"] },
  ),
  goblinRabblemaster: card(
    "Goblin Rabblemaster",
    "Creature — Goblin Warrior",
    "Other Goblin creatures you control attack each combat if able. At the beginning of combat on your turn, create a 1/1 red Goblin creature token with haste. Whenever Goblin Rabblemaster attacks, create a 1/1 red Goblin creature token that's tapped and attacking.",
    { colors: ["R"], manaValue: 3 },
  ),
  anathemancer: card(
    "Anathemancer",
    "Creature — Zombie Wizard",
    "When Anathemancer enters the battlefield, it deals damage to target player equal to the number of nonbasic lands that player controls.",
    { colors: ["B", "R"], manaValue: 3, keywords: ["Unearth"] },
  ),
  angelOfInvention: card(
    "Angel of Invention",
    "Creature — Angel",
    "Flying, vigilance. Fabricate 2. Other creatures you control get +1/+1.",
    { colors: ["W"], manaValue: 5, keywords: ["Flying", "Vigilance", "Fabricate"] },
  ),
  parallelLives: card(
    "Parallel Lives",
    "Enchantment",
    "If an effect would create one or more tokens under your control, it creates twice that many of those tokens instead.",
    { colors: ["G"], manaValue: 4 },
  ),
  monasterySwiftspear: card(
    "Monastery Swiftspear",
    "Creature — Human Monk",
    "Prowess (Whenever you cast a noncreature spell, this creature gets +1/+1 until end of turn.)",
    { colors: ["R"], manaValue: 1, keywords: ["Haste", "Prowess"] },
  ),
  grapeshot: card(
    "Grapeshot",
    "Sorcery",
    "Grapeshot deals 1 damage to any target.",
    { colors: ["R"], manaValue: 1, keywords: ["Storm"] },
  ),
  mycoloth: card(
    "Mycoloth",
    "Creature — Fungus",
    "Devour 1 (As this enters the battlefield, you may sacrifice any number of creatures. This creature enters the battlefield with that many +1/+1 counters on it.) At the beginning of your upkeep, create a 1/1 green Saproling creature token for each +1/+1 counter on Mycoloth.",
    { colors: ["G"], manaValue: 5, keywords: ["Devour"] },
  ),
  titheTaker: card(
    "Tithe Taker",
    "Creature — Human Advisor",
    "During your turn, spells your opponents cast cost {1} more and abilities your opponents activate cost {1} more unless they're mana abilities. Afterlife 1 (When this creature dies, create a 1/1 white and black Spirit creature token with flying.)",
    { colors: ["W"], manaValue: 2, keywords: ["Afterlife"] },
  ),
  sokenzanSmelter: card(
    "Sokenzan Smelter",
    "Creature — Ogre Shaman",
    "Blitz {2}{R}{R} (You may cast this spell for its blitz cost. If you do, it gains haste and \"When this creature dies, draw a card.\" Sacrifice it at the beginning of the next end step.) When Sokenzan Smelter enters the battlefield, it deals 2 damage to any target.",
    { colors: ["R"], manaValue: 4, keywords: ["Blitz"] },
  ),
  maverickThopterist: card(
    "Maverick Thopterist",
    "Creature — Human Artificer",
    "Improvise (Your artifacts can help cast this spell. Each artifact you tap after you're done activating mana abilities pays for {1}.) When Maverick Thopterist enters the battlefield, create two 1/1 colorless Thopter artifact creature tokens with flying.",
    { colors: ["U"], manaValue: 5, keywords: ["Improvise"] },
  ),
  chordOfCalling: card(
    "Chord of Calling",
    "Instant",
    "Convoke (Your creatures can help cast this spell. Each creature you tap while casting this spell pays for {1} or one mana of that creature's color.) Search your library for a creature card, put it onto the battlefield, then shuffle.",
    { colors: ["G"], manaValue: 3, keywords: ["Convoke"] },
  ),
  craterhoofBehemoth: card(
    "Craterhoof Behemoth",
    "Creature — Beast",
    "Haste. When Craterhoof Behemoth enters the battlefield, creatures you control gain trample and get +X/+X until end of turn, where X is the number of creatures you control.",
    { colors: ["G"], manaValue: 8, keywords: ["Haste", "Trample"] },
  ),
  thrabenInspector: card(
    "Thraben Inspector",
    "Creature — Human Soldier",
    "When Thraben Inspector enters the battlefield, investigate. (Create a Clue token. It's an artifact with \"{2}, Sacrifice this artifact: Draw a card.\")",
    { colors: ["W"], manaValue: 1, keywords: ["Investigate"] },
  ),
  gildedGoose: card(
    "Gilded Goose",
    "Creature — Bird",
    "Flying. When Gilded Goose enters the battlefield, create a Food token.",
    { colors: ["G"], manaValue: 1, keywords: ["Flying", "Food"] },
  ),
  whisperwoodElemental: card(
    "Whisperwood Elemental",
    "Creature — Elemental",
    "At the beginning of your end step, manifest the top card of your library.",
    { colors: ["G"], manaValue: 5, keywords: ["Manifest"] },
  ),
  rancor: card(
    "Rancor",
    "Enchantment — Aura",
    "Enchant creature. Enchanted creature gets +2/+0 and has trample. When Rancor is put into a graveyard from the battlefield, return Rancor to its owner's hand.",
    { colors: ["G"], manaValue: 1 },
  ),
  korSpiritdancer: card(
    "Kor Spiritdancer",
    "Creature — Kor Wizard",
    "Whenever you cast an Aura spell, draw a card. Kor Spiritdancer gets +2/+2 for each Aura attached to it.",
    { colors: ["W"], manaValue: 2 },
  ),
  boonSatyr: card(
    "Boon Satyr",
    "Enchantment Creature — Satyr",
    "Flash. Bestow {3}{G}{G}. Enchanted creature gets +4/+2. As long as this isn't attached to a creature, it's a creature in addition to its other types.",
    { colors: ["G"], manaValue: 4, keywords: ["Flash", "Bestow"] },
  ),
  kindredDiscovery: card(
    "Kindred Discovery",
    "Enchantment",
    "As this enchantment enters, choose a creature type. Whenever a creature you control of the chosen type enters or attacks, draw a card.",
    { colors: ["U"], manaValue: 5 },
  ),
  archmageOfEchoes: card(
    "Archmage of Echoes",
    "Creature — Faerie Wizard",
    "Flying, ward {2}. Whenever you cast a Faerie or Wizard permanent spell, copy it. (The copy becomes a token.)",
    { colors: ["U"], manaValue: 4, keywords: ["Flying", "Ward"] },
  ),
  academyWizard: card(
    "Academy Wizard",
    "Creature — Human Wizard",
    "",
    { colors: ["U"], manaValue: 2 },
  ),
  changelingHost: card(
    "Woodland Changeling",
    "Creature — Shapeshifter",
    "Changeling (This card is every creature type.)",
    { colors: ["G"], manaValue: 2, keywords: ["Changeling"] },
  ),
  partyPayoff: card(
    "Acquisitions Expert",
    "Creature — Human Rogue",
    "When Acquisitions Expert enters the battlefield, you may reveal the top cards of your library for each creature in your party, then put revealed creature cards into your hand. (Your party consists of up to one each of a Cleric, Rogue, Warrior, and Wizard.)",
    { colors: ["B"], manaValue: 4 },
  ),
  dualTribalPayoff: card(
    "Dual Tribal Payoff",
    "Enchantment",
    "As this enchantment enters, choose a creature type. Wizards you control get +1/+1. Whenever a creature you control of the chosen type enters, draw a card.",
    { colors: ["U"], manaValue: 4 },
  ),
  typeSweeper: card(
    "Type Sweeper",
    "Sorcery",
    "Choose a card type. Destroy all permanents of that type.",
    { colors: ["W"], manaValue: 5 },
  ),
  partyFlavor: card(
    "Party Crasher",
    "Instant",
    "Target creature can't block this turn. It was quite the party.",
    { colors: ["R"], manaValue: 1 },
  ),
  wizardLord: card(
    "Wizard Lord",
    "Creature — Human Wizard",
    "Other Wizards you control get +1/+1.",
    { colors: ["U"], manaValue: 3 },
  ),
  nontokenWizardPayoff: card(
    "Eminent Archmage",
    "Legendary Creature — Human Wizard",
    "Whenever a nontoken Wizard you control enters, draw a card.",
    { colors: ["U"], manaValue: 4 },
  ),
};
