import { expect, test } from "vitest";
import TEMPLATE from "./template-targets.json" with { type: "json" };
import { ARCHETYPE_VOCABULARY } from "./archetype-vocabulary.js";

/** THE DATA FILE'S RATCHET (spec `2026-09-06-theme-template-proposal.md` §3.1). Regenerated by
 *  `research/template-fit.ts`; these are the properties a hand edit or a re-pull must keep. */
const KEYS = ["consistency", "ramp", "interaction", "boardWipes"] as const;
const themes = TEMPLATE.themes as Record<string, Record<string, number>>;

test("the file is versioned and carries its provenance", () => {
  expect(TEMPLATE.version).toBeGreaterThan(0);
  expect(TEMPLATE.source).toMatch(/decks/);
});

test("every theme key is a vocabulary member, and none is goodstuff or a land count", () => {
  const slugs = new Set<string>(ARCHETYPE_VOCABULARY.map((r) => r.slug));
  for (const name of Object.keys(themes)) expect(slugs.has(name), `${name} is not a vocabulary member`).toBe(true);
  expect(themes.goodstuff, "goodstuff's population is cEDH midrange and must not be a row (spec §5)").toBeUndefined();
  for (const row of Object.values(themes)) expect(row.lands, "lands are Karsten's, never the file's").toBeUndefined();
});

test("every value sits inside the population's observed range, and every row says its n", () => {
  for (const [name, row] of Object.entries(themes)) {
    expect(row.n, `${name} has no n`).toBeGreaterThanOrEqual(5);
    for (const k of KEYS) {
      if (row[k] === undefined) continue;
      const [lo, hi] = TEMPLATE.range[k];
      expect(row[k], `${name}.${k}`).toBeGreaterThanOrEqual(lo);
      expect(row[k], `${name}.${k}`).toBeLessThanOrEqual(hi);
    }
    for (const k of ["consistency", "ramp", "interaction"] as const) expect(row[k], `${name}.${k} missing`).toBeDefined();
  }
  for (const k of KEYS) expect(TEMPLATE.population[k]).toBeGreaterThan(0);
});

test("a boardWipes row is present only where the theme leans by more than one (owner ruling: wipes stay doctrine)", () => {
  for (const [name, row] of Object.entries(themes)) {
    if (row.boardWipes === undefined) continue;
    expect(Math.abs(row.boardWipes - TEMPLATE.population.boardWipes), `${name} carries a wipes row it does not need`).toBeGreaterThan(1);
  }
});

test("the rows the spec cites are in the file, at the values the population measured", () => {
  // The three the report will show first, and the one every review asks about.
  expect(themes.voltron!.interaction).toBeGreaterThan(TEMPLATE.population.interaction + 4);
  expect(themes.superfriends!.boardWipes).toBeGreaterThanOrEqual(6);
  expect(themes.treasure!.ramp).toBeGreaterThan(TEMPLATE.population.ramp + 8);
});
