/** AC1 PROBES: for each rule-defined event the head census could not see by its verb alone, the
 *  commander-legal count and three witness lines. Free, read-only. */
import { connect, loadConfig } from "@edh-seer/data";
const store = await connect(loadConfig());
const cards = await store.cards
  .find({ "legalities.commander": "legal" } as never, { projection: { name: 1, oracleText: 1 } })
  .toArray() as unknown as { name: string; oracleText?: string }[];
const PROBES: [string, RegExp][] = [
  ["foretold", /(when|whenever)[^.]{0,40}\bforetell/i],
  ["regenerated", /(when|whenever)[^.]{0,40}\bregenerat/i],
  ["mentors", /(when|whenever)[^.]{0,40}\bmentors?\b/i],
  ["gift", /(when|whenever)[^.]{0,40}\bgives? a gift/i],
  ["renowned", /(when|whenever)[^.]{0,40}\brenowned/i],
  ["plotted", /(when|whenever)[^.]{0,40}\bplot/i],
  ["saddled", /(when|whenever)[^.]{0,40}\bsaddle/i],
  ["goaded", /(when|whenever)[^.]{0,40}\bgoad/i],
  ["solved", /(when|whenever)[^.]{0,40}\bsolve/i],
  ["defeated (battle)", /(when|whenever)[^.]{0,40}\bdefeat/i],
  ["speed", /(when|whenever)[^.]{0,40}\bspeed\b/i],
  ["mana added", /(when|whenever)[^.]{0,40}\badds? (one or more )?(mana|\{)/i],
  ["returned to hand", /(when|whenever)[^.]{0,50}\b(returned|return) [^.]{0,30}\bhand/i],
  ["put on top/into library", /(when|whenever)[^.]{0,50}\bput (on top of|into|on the bottom of) [^.]{0,15}librar/i],
  ["poison", /(when|whenever)[^.]{0,40}\bpoison/i],
  ["becomes a creature", /(when|whenever)[^.]{0,40}\bbecomes? an? [^.]{0,20}creature\b/i],
  ["kicked", /(when|whenever)[^.]{0,40}\bkick/i],
  ["energy", /(when|whenever)[^.]{0,40}\{E\}/i],
  ["suspected", /(when|whenever)[^.]{0,40}\bsuspect/i],
  ["exerted", /(when|whenever)[^.]{0,40}\bexert/i],
  ["counter removed", /(when|whenever)[^.]{0,60}\b(remove|removed)\b[^.]{0,30}\bcounters?\b|(when|whenever)[^.]{0,60}\bcounters? [^.]{0,20}(is|are) removed/i],
  ["mana spent/paid", /(when|whenever)[^.]{0,40}\b(spend|spent|pay|pays|paid)\b[^.]{0,30}(mana|\{|cost|life)/i],
  ["state: control no/have no", /(when|whenever)[^.]{0,30}\b(control|have|has) (no|fewer|more|seven|\d)/i],
  ["state: there are N", /(when|whenever) there (are|is) (no|\w+ or more|\w+ or fewer)/i],
  ["unattached", /(when|whenever)[^.]{0,40}\bunattached/i],
  ["ring-bearer chosen", /(when|whenever)[^.]{0,40}\bring-bearer/i],
  ["countered (spell)", /(when|whenever)[^.]{0,60}\bcounters? (a|that|target|one or more)? ?spell|(when|whenever)[^.]{0,40}\b(is|are) countered/i],
  ["explores", /(when|whenever)[^.]{0,40}\bexplores?\b/i],
  ["a spell is copied", /(when|whenever)[^.]{0,40}\bcop(y|ies)\b/i],
  ["fights", /(when|whenever)[^.]{0,40}\bfights?\b/i],
  ["assigned damage / excess", /(when|whenever)[^.]{0,40}\bexcess damage/i],
  ["deals damage (any)", /(when|whenever)[^.]{0,60}\bdeals? [^.]{0,20}damage/i],
  ["max speed", /(when|whenever)[^.]{0,40}\bmax speed/i],
  ["offspring/token copy", /(when|whenever)[^.]{0,40}\boffspring/i],
  ["surveil", /(when|whenever)[^.]{0,40}\bsurveil/i],
  ["shuffles", /(when|whenever)[^.]{0,40}\bshuffl/i],
  ["stickers", /(when|whenever)[^.]{0,40}\bsticker/i],
  ["votes", /(when|whenever)[^.]{0,40}\bvot(e|es|ing)\b/i],
  ["morph face down", /(when|whenever)[^.]{0,40}\bface[- ]down\b/i],
  ["assembled/contraption", /(when|whenever)[^.]{0,40}\bcontraption/i],
  ["end the turn", /(when|whenever)[^.]{0,40}\bend the turn/i],
  ["extra turn taken", /(when|whenever)[^.]{0,40}\bextra turn/i],
  ["additional combat", /(when|whenever)[^.]{0,40}\badditional combat/i],
  ["becomes suspended / suspend", /(when|whenever)[^.]{0,40}\bsuspend/i],
  ["last time counter removed", /last time counter is removed/i],
  ["becomes untapped", /(when|whenever)[^.]{0,40}\bbecomes? untapped/i],
  ["tapped for mana", /(when|whenever)[^.]{0,40}\btapped for mana/i],
  ["blocks or becomes blocked", /(when|whenever)[^.]{0,40}\bbecomes? blocked/i],
  ["dealt damage", /(when|whenever)[^.]{0,60}\b(is|are) dealt/i],
  ["a player loses the game", /(when|whenever)[^.]{0,40}\bloses? the game/i],
  ["wins the game", /(when|whenever)[^.]{0,40}\bwins? the game/i],
  ["a spell resolves", /(when|whenever)[^.]{0,40}\bresolves?\b/i],
  ["ability is activated/triggers", /(when|whenever)[^.]{0,40}\babilit(y|ies)[^.]{0,20}\b(triggers?|is activated|resolves?)/i],
  ["a player searches", /(when|whenever)[^.]{0,40}\bsearch/i],
  ["ninjutsu/put onto battlefield", /(when|whenever)[^.]{0,50}\bput onto the battlefield\b/i],
  ["a permanent is exiled", /(when|whenever)[^.]{0,50}\b(is|are) exiled\b|(when|whenever)[^.]{0,40}\bexiles?\b/i],
  ["target is chosen / becomes target", /(when|whenever)[^.]{0,40}\bbecomes? the target/i],
  ["becomes monarch", /(when|whenever)[^.]{0,40}\bmonarch/i],
  ["takes the initiative", /(when|whenever)[^.]{0,40}\binitiative/i],
  ["a Class levels", /(when|whenever)[^.]{0,40}\blevel/i],
  ["a Room unlocks", /(when|whenever)[^.]{0,40}\bunlock/i],
  ["day/night", /(when|whenever)[^.]{0,40}\b(becomes? (day|night))/i],
  ["a dungeon is completed", /(when|whenever)[^.]{0,40}\bcomplete[^.]{0,10}dungeon/i],
  ["venture", /(when|whenever)[^.]{0,40}\bventure/i],
  ["crime", /(when|whenever)[^.]{0,40}\bcommit[^.]{0,5}crime/i],
  ["expend", /(when|whenever)[^.]{0,40}\bexpend/i],
  ["descend", /(when|whenever)[^.]{0,40}\bdescend/i],
  ["gains control", /(when|whenever)[^.]{0,40}\bgains? control/i],
  ["loses control", /(when|whenever)[^.]{0,40}\bloses? control/i],
  ["phases out/in", /(when|whenever)[^.]{0,40}\bphases? (out|in)/i],
  ["transforms", /(when|whenever)[^.]{0,40}\btransform/i],
  ["becomes attached", /(when|whenever)[^.]{0,40}\battached/i],
  ["prevented", /(when|whenever)[^.]{0,40}\bprevent/i],
  ["flips a coin / wins flip", /(when|whenever)[^.]{0,40}\b(flip|coin)/i],
  ["rolls a die", /(when|whenever)[^.]{0,40}\broll/i],
  ["clash", /(when|whenever)[^.]{0,40}\bclash/i],
  ["ring tempts", /(when|whenever)[^.]{0,40}\bring tempts/i],
  ["proliferate", /(when|whenever)[^.]{0,40}\bproliferate/i],
  ["turned face up", /(when|whenever)[^.]{0,40}\bturned face up/i],
  ["mutates", /(when|whenever)[^.]{0,40}\bmutates?\b/i],
  ["becomes crewed", /(when|whenever)[^.]{0,40}\bcrewed/i],
  ["cycles", /(when|whenever)[^.]{0,40}\bcycl/i],
  ["milled", /(when|whenever)[^.]{0,40}\bmill/i],
  ["a card is revealed", /(when|whenever)[^.]{0,40}\breveal/i],
  ["a token is created", /(when|whenever)[^.]{0,40}\bcreate/i],
  ["a land is played", /(when|whenever)[^.]{0,40}\bplays? a land/i],
  ["when you do (reflexive)", /\bwhen you do\b/i],
  ["when they do (reflexive)", /\bwhen (they|that player) do(es)?\b/i],
  ["becomes the target of an opponent (ward)", /\bward\b/i],
  ["amass", /(when|whenever)[^.]{0,40}\bamass/i],
  ["exploits", /(when|whenever)[^.]{0,40}\bexploit/i],
  ["investigate", /(when|whenever)[^.]{0,40}\binvestigate/i],
  ["bend (fire/water/earth/air)", /(when|whenever)[^.]{0,40}\b(fire|water|earth|air)bend/i],
  ["forages", /(when|whenever)[^.]{0,40}\bforage/i],
  ["the most / tied", /(when|whenever)[^.]{0,40}\bthe most\b/i],
];
for (const [label, re] of PROBES) {
  const hits = cards.filter((c) => re.test((c.oracleText ?? "").replace(/\([^)]*\)/g, "")));
  const lines = hits.slice(0, 3).map((c) => {
    const l = (c.oracleText ?? "").replace(/\([^)]*\)/g, "").split("\n").find((x) => re.test(x)) ?? "";
    return `${c.name}: ${l.slice(0, 110)}`;
  });
  console.log(`${String(hits.length).padStart(5)}  ${label}\n${lines.map((l) => `         ${l}`).join("\n")}`);
}
await store.close(); process.exit(0);
