/** EVERY SECTION OF THE COMPREHENSIVE RULES, WITH THE ENGINE'S VERDICT (roadmap AC9, 2026-09-09).
 *
 *  Everything found before the sweep was found because someone THOUGHT OF IT. CR 114 (emblems) was
 *  wrong for a month — the word existed, the derive mapped it to tokens — and no instrument could
 *  say so because the section had no row to be wrong in. So this is one row per section, all 147
 *  at rules 20260819, and `cr-sections.test.ts` fails on a section without a row: when WotC adds
 *  734, it is judged or the build is red.
 *
 *  A verdict says what the ENGINE does with the section: MODELLED (a real shape exists), PARTIAL
 *  (some of it), OPEN (nothing, and the section reaches cards), N/A (nothing, and it cannot reach an
 *  EDH decklist or is not a card-facing rule). `probe` / `typeLine` / `layout` size a row against
 *  the corpus; `research/tagger/cr-section-sweep.ts` prints the table with those counts. */
export type Verdict = "MODELLED" | "PARTIAL" | "OPEN" | "N/A";
export interface Status { verdict: Verdict; note: string; probe?: RegExp; typeLine?: RegExp; layout?: string }

/** One row per CR 7xx section. `probe` counts the corpus cards the section can reach, so an OPEN row
 *  carries its own size and the list can be ranked rather than merely listed. */
export const SECTIONS: Record<string, Status> = {
  "700": { verdict: "PARTIAL", note: "general concepts; modified/outlaw/party/descended still unmodelled as subject filters" },
  "701": { verdict: "MODELLED", note: "keyword actions — complete + ratcheted by cr-completeness.test.ts" },
  "702": { verdict: "PARTIAL", note: "keyword abilities — 5 short of the CR (was 6; MTGJSON caught up on `storied` 2026-08-20), ratcheted as MTGJSON_LAG" },
  "703": { verdict: "PARTIAL", note: "turn-based actions — SWEPT 2026-08-20, all 13 of 703.4 judged: phasing/day-night/untap/draw/lore/attackers/blockers/combat damage/cleanup all have trigger words, scheme + Attractions are N/A on legality, defending-player choice is the 800-series opponent gap, damage removal and mana emptying carry no printed trigger (0 corpus cards). Residue was `phases-in`, now a word." },
  "704": { verdict: "PARTIAL", note: "state-based actions — Sagas closed 2026-08-15, the 704.5j legend rule closed 2026-08-19 (copy-of-a-legend dies); 0-loyalty and poison open" },
  "705": { verdict: "OPEN", note: "coin flips — no event, no vocabulary", probe: /flips? a coin/i },
  "706": { verdict: "PARTIAL", note: "dice — `dice-rolled` trigger added 2026-08-15, no effect model", probe: /rolls? a d/i },
  "707": { verdict: "PARTIAL", note: "copying — `copy` verb and trigger exist; 707.2 (a copy has the copied abilities, so its entry trigger fires) shipped 2026-08-19; still no model of what a copy IS" },
  "708": { verdict: "OPEN", note: "face-down spells/permanents — manifest and cloak emit `enters`, nothing knows they are face down", probe: /face down/i },
  "709": { verdict: "MODELLED", note: "split cards — playableFaces lists both halves", layout: "split" },
  "710": { verdict: "MODELLED", note: "flip cards — FRONT_FACE_ONLY allow-list", layout: "flip" },
  "711": { verdict: "PARTIAL", note: "leveler cards — `level-up` trigger exists, level bands unmodelled", layout: "leveler" },
  "712": { verdict: "MODELLED", note: "double-faced cards — DERIVE_VERSION 30, one face at a time" },
  "713": { verdict: "N/A", note: "substitute cards are a physical-play convenience" },
  "714": { verdict: "MODELLED", note: "Saga — sagaEvents ships the 714.4 self-sacrifice", typeLine: /Saga/ },
  "715": { verdict: "OPEN", note: "Adventurer — 715.3d exile-then-playable unmodelled; 715.4 zone types WRONG (see gap-sweep stub §3.2)", layout: "adventure" },
  "716": { verdict: "OPEN", note: "Class cards — class levels unmodelled entirely", typeLine: /Class/ },
  "717": { verdict: "N/A", note: "Attractions live in a separate deck, never the 99" },
  "718": { verdict: "OPEN", note: "Prototype — alternative cost AND different characteristics, the adventure shape again", probe: /\bPrototype\b/i },
  "719": { verdict: "OPEN", note: "Case cards — solve condition unmodelled", typeLine: /— Case/ },
  "720": { verdict: "OPEN", note: "Omen — 720.3d shuffles into library, never a graveyard; unmodelled" },
  "721": { verdict: "MODELLED", note: "Station — charge counters via KEYWORD_EMITS" },
  "722": { verdict: "PARTIAL", note: "Preparation cards — playableFaces lists the faces, the prepare mechanic itself is unmodelled", layout: "prepare" },
  "723": { verdict: "N/A", note: "controlling another player — 2 corpus cards, no synergy shape" },
  "724": { verdict: "OPEN", note: "ending turns and phases — 'end the turn' skips everything, invisible to the clock model", probe: /end the turn/i },
  "725": { verdict: "MODELLED", note: "monarch — trigger word added 2026-08-15" },
  "726": { verdict: "MODELLED", note: "initiative — trigger word added 2026-08-15" },
  "727": { verdict: "N/A", note: "restarting the game — 2 corpus cards" },
  "728": { verdict: "MODELLED", note: "rad counters — already in COUNTER_KINDS", probe: /rad counter/i },
  "729": { verdict: "N/A", note: "subgames — Shahrazad and friends, not EDH-relevant" },
  "730": { verdict: "OPEN", note: "merging with permanents — mutate; a merged permanent is several cards in one", probe: /\bmutate\b/i },
  "731": { verdict: "MODELLED", note: "day and night — trigger word added 2026-08-15" },
  "732": { verdict: "N/A", note: "taking shortcuts is a play convention" },
  "733": { verdict: "N/A", note: "handling illegal actions is a judge procedure" },

  // --- BANDS 1xx-6xx, judged individually 2026-08-15 after the owner asked whether any other
  // sections had been looked at. They had not; these are the ones that turned out to matter.
  "104": { verdict: "PARTIAL", note: "ending the game — `win-game` kind exists; 'loses the game' is a REFUSED trigger (LOSES_THE_GAME)", probe: /wins? the game|loses? the game/i },
  "111": { verdict: "MODELLED", note: "tokens — `token` tri-state on every subject, token-types.json from the tokens collection" },
  "113": { verdict: "MODELLED", note: "abilities — 113.3's four categories map to AbilityKind" },
  "115": { verdict: "PARTIAL", note: "targets — `becomes-target` trigger exists; nothing models WHAT a spell targets, so heroic-shaped payoffs have no supply" },
  "116": { verdict: "PARTIAL", note: "special actions — SWEPT 2026-08-20, all 12 of 116.2 judged: playing a land reaches the engine as `enters`, turning face up has both a verb and a trigger (119 trigger clauses), Rooms unlocking has `unlocked`, suspend/companion/foretell are keywords with no event anyone watches, Circling Vultures is a discard, planar die and conspiracies are N/A on legality. The one real hole is `plot` (116.2k), already tracked as MTGJSON lag. 708 face-down is still the same hole from the other side.", probe: /turn .{0,20}face up/i },
  "118": { verdict: "OPEN", note: "costs — additional and alternative costs unmodelled; Ability.cost holds the STRING and nothing parses it", probe: /rather than pay|without paying its mana cost/i },
  "122": { verdict: "MODELLED", note: "counters — COUNTER_KINDS, fixed against 122.1b (a18a969)" },
  "205": { verdict: "MODELLED", note: "type line — types/subtypes/supertypes generated from MTGJSON with a --check gate" },
  "310": { verdict: "OPEN", note: "Battles — a CARD TYPE, in the type vocabulary but with no defense/siege model", typeLine: /Battle/ },
  "604": { verdict: "PARTIAL", note: "static abilities — 604.3 characteristic-defining abilities unmodelled, so Tarmogoyf derives nothing" },
  "607": { verdict: "OPEN", note: "linked abilities — 'exiled with' pairs; the per-clause shared-trigger ceiling is this", probe: /exiled with/i },
  "611": { verdict: "PARTIAL", note: "continuous effects — statics derive, layers do not; `namesItsTargets` is the only mesh guard" },
  "614": { verdict: "OPEN", note: "REPLACEMENT EFFECTS — the largest gap in the engine. No shape for 'if X would Y, instead Z'", probe: /\bwould\b[^.]{0,80}\binstead\b/i },
  "615": { verdict: "OPEN", note: "prevention effects — 'prevent' has no model; a prevented damage still emits", probe: /\bprevent\b/i },

  // --- MULTIPLAYER (800s) and VARIANTS (900s). EDH is a multiplayer variant, so these are not
  // optional colour: 903 IS the format. Swept 2026-08-15 after the 7xx pass.
  "800": { verdict: "PARTIAL", note: "multiplayer general — the engine models no opponent at all; every number is optimistic by construction" },
  "801": { verdict: "N/A", note: "limited range of influence — not used in EDH" },
  "802": { verdict: "OPEN", note: "attack multiple players — the pressure clock accumulates against ONE opponent's 40" },
  "806": { verdict: "PARTIAL", note: "free-for-all is the EDH shape; pod analysis is a known blocked item" },
  "903": { verdict: "PARTIAL", note: "COMMANDER — `SubjectFilter.commander` SHIPPED 2026-08-15 (a deck fact per 903.3, stamped by markCommander); 903.5a-d LEGALITY shipped 2026-08-25 as a report (`legality.ts`, incl. colour identity and who may lead); 903.8 commander tax ships as a CAVEAT and not a number, because the tax follows how often the commander has DIED and nothing here simulates a game; Partner/Background pairing is still unmodelled (J12)", probe: /\b(a |your )commanders?\b(?! damage)/i },

  // --- THE REST OF THE RULEBOOK, judged 2026-09-09 (roadmap AC9). Every section now has a row and
  // `cr-sections.test.ts` fails on one that does not, so CR 114 (emblems, wrong for a month with no
  // row to be wrong in) cannot happen again by omission. A verdict says what the ENGINE does with
  // the section, not whether the section is interesting; most of 1xx-2xx are N/A because the rules
  // describe the game's bookkeeping, not anything a card can synergise on.
  "100": { verdict: "N/A", note: "how to read the rules" },
  "101": { verdict: "N/A", note: "golden rules (can't beats can, etc.) — a judge's tool, no card shape" },
  "102": { verdict: "PARTIAL", note: "players — the engine models ONE player; opponents exist only as `control: opponent` on subjects (800 is the same gap)" },
  "103": { verdict: "MODELLED", note: "starting the game — 40 life and the commander in the command zone are the goldfish's initial state (903)" },
  "105": { verdict: "MODELLED", note: "colours — `colors`/`colorIdentity` characteristics, colour chips exact on both pages (owner 2026-09-08), legality by identity" },
  "106": { verdict: "MODELLED", note: "mana — the mana model end to end (2026-08-26 log): coloured sources, tap-replacements, `tapped-for-mana`; 106.12a is the trigger" },
  "107": { verdict: "PARTIAL", note: "numbers and symbols — {X} has no deadline (the castability defect the cost-to-effect work is blocked on); {E} is an energy counter (107.14, prompt rule 2026-09-09)", probe: /\{X\}/ },
  "108": { verdict: "MODELLED", note: "cards — owner/controller: `control` on every subject; a card's identity is its oracle id" },
  "109": { verdict: "MODELLED", note: "objects — cards, tokens (111) and emblems (114) are each nodes; a face is a node since 2026-08-27" },
  "110": { verdict: "PARTIAL", note: "permanents and status — tapped/untapped are events (`taps`/`untaps`), face-down is 708's open hole, phased is `phases-in/out` words with no emit", probe: /\bface down\b/i },
  "112": { verdict: "PARTIAL", note: "spells — `cast`, `copy` (kind clone, no emit), `counter-spell` since 2026-09-09; a spell's own on-cast abilities are `on-cast`" },
  "114": { verdict: "MODELLED", note: "EMBLEMS — nodes since 2026-09-08 (PR #268): Scryfall emblem objects as identity, `creates:emblem`, flipPerspective for an opponent's. This is the row that was missing." },
  "117": { verdict: "PARTIAL", note: "timing and priority — instant speed is `castAtInstantSpeed` (an Instant or flash); split second, stack timing and 'any time you could cast an instant' are not modelled", probe: /\bany time you could cast an instant\b|\bflash\b/i },
  "119": { verdict: "MODELLED", note: "life — `gain-life`/`lose-life` emits, `life-gained`/`life-lost` words, drain merges the pair; paying life is losing life (118.3b prompt rule)" },
  "120": { verdict: "PARTIAL", note: "damage — combat vs non-combat split by text; the RECEIVING side (`damaged`, 122 cards) has a word and no engine verb; excess damage (120.10) unmodelled" },
  "121": { verdict: "MODELLED", note: "drawing — `draw` emit and word, controller default, replacement draws refused as events (614 prompt rule)" },
  "123": { verdict: "N/A", note: "stickers — Unfinity sticker sheets, excluded with Attractions (9 cards, 0 bought)" },
  "200": { verdict: "N/A", note: "parts of a card, general" },
  "201": { verdict: "MODELLED", note: "name — self-reference by name is `SubjectFilter.self`, the biggest false-edge family this engine had" },
  "202": { verdict: "MODELLED", note: "mana cost and colour — castability, MV (nonlands only, owner ruling), colour identity" },
  "203": { verdict: "N/A", note: "illustration — not a game characteristic" },
  "204": { verdict: "MODELLED", note: "colour indicator — Scryfall's `colors` already folds it in" },
  "206": { verdict: "N/A", note: "expansion symbol — printings are runtime, never cached" },
  "207": { verdict: "MODELLED", note: "text box — the oracle text IS the input; reminder text stripped by segment()" },
  "208": { verdict: "MODELLED", note: "power/toughness — `StatPredicate`, characteristics; */* refused as a number" },
  "209": { verdict: "MODELLED", note: "loyalty — loyalty abilities and the loyalty badge (2026-09-08)" },
  "210": { verdict: "OPEN", note: "defense — battles have no defense model (see 310)", probe: /\bdefense counter/i },
  "211": { verdict: "N/A", note: "hand modifier — Vanguard only" },
  "212": { verdict: "N/A", note: "life modifier — Vanguard only" },
  "213": { verdict: "N/A", note: "information below the text box — collector data" },
  "300": { verdict: "MODELLED", note: "card types — generated from MTGJSON with a --check gate (205)" },
  "301": { verdict: "PARTIAL", note: "artifacts — Equipment attach/unattach are words with no emit (OPEN verbs `attach`, `unattach`); Vehicles crew is `becomes-crewed`" },
  "302": { verdict: "MODELLED", note: "creatures — the most modelled type: stats, combat events, tokens" },
  "303": { verdict: "PARTIAL", note: "enchantments — Auras attach (301's gap), Sagas modelled (714), Rooms `unlocked`; enchanted-permanent references resolve through `enchantText`" },
  "304": { verdict: "MODELLED", note: "instants — `castAtInstantSpeed`" },
  "305": { verdict: "MODELLED", note: "lands — `land-play` implied event, fetch edges (owner ruling 2026-09-06), Wastes shares no type" },
  "306": { verdict: "MODELLED", note: "planeswalkers — loyalty abilities, emblems, `damage-dealt` to planeswalkers" },
  "307": { verdict: "MODELLED", note: "sorceries — sorcery speed is the default" },
  "308": { verdict: "MODELLED", note: "kindreds — the type vocabulary carries Kindred (not Tribal, owner 2026-09-06); 0 cards print the word in rules text" },
  "309": { verdict: "PARTIAL", note: "dungeons — `venture-into-the-dungeon` and `dungeon-completed` are words; no room-by-room model (15 venture cards, 5 completion consumers)" },
  "311": { verdict: "N/A", note: "planes — Planechase, never in a decklist (238 cards excluded)" },
  "312": { verdict: "N/A", note: "phenomena — Planechase" },
  "313": { verdict: "N/A", note: "vanguards — Vanguard" },
  "314": { verdict: "N/A", note: "schemes — Archenemy (84 cards excluded)" },
  "315": { verdict: "N/A", note: "conspiracies — Conspiracy Draft" },
  "400": { verdict: "MODELLED", note: "zones, general — 400.7 zone changes are the enters/leaves/dies/exiled family; ZONES lists the seven" },
  "401": { verdict: "PARTIAL", note: "library — search/scry/surveil/mill events; `put-into-library` is a word with no emit (2 consumers)" },
  "402": { verdict: "PARTIAL", note: "hand — draw/discard events; `returned-to-hand` a word with no emit (5, all in the bought tail); maximum hand size is `other`", probe: /\bmaximum hand size\b/i },
  "403": { verdict: "MODELLED", note: "battlefield — enters/leaves/dies, the engine's home zone" },
  "404": { verdict: "MODELLED", note: "graveyard — `enters-graveyard` (origin-blind), dies, mill, discard; graveyard-recursion and -hate kinds" },
  "405": { verdict: "PARTIAL", note: "stack — `counter-spell` since 2026-09-09; copying a spell is the `clone`/`copy-spell` kind with no emit; `resolves` a word (2)" },
  "406": { verdict: "OPEN", note: "exile — `exiled` is a word (58 trigger consumers) and the `exile` action emits only a battlefield `leaves`; exile from a graveyard/library/hand emits nothing (892 dropped)", probe: /(when|whenever)[^.]{0,50}\b(is|are) (put into exile|exiled)\b/i },
  "407": { verdict: "N/A", note: "ante — not sanctioned" },
  "408": { verdict: "PARTIAL", note: "command zone — the commander (903) and emblems (114) live here and are modelled; casting from it is the commander tax caveat, not a number", probe: /\bcommand zone\b/i },
  "500": { verdict: "MODELLED", note: "turn structure — every phase and step is a TRIGGERS word; nothing emits one by design (the turn supplies it)" },
  "501": { verdict: "MODELLED", note: "beginning phase — `untap-step`, `upkeep`, `draw-step`" },
  "502": { verdict: "MODELLED", note: "untap step — `untap-step`; 502.1 phasing is `phases-in/out`, 502.2 day/night is `day-night`" },
  "503": { verdict: "MODELLED", note: "upkeep — `upkeep`, an engine verb; the commonest phase trigger (892 cards)" },
  "504": { verdict: "MODELLED", note: "draw step — `draw-step`; the turn's draw is not a card's `draw` emit" },
  "505": { verdict: "MODELLED", note: "main phase — `main-phase`; Saga lore counters (505.4) are `chapter`" },
  "506": { verdict: "MODELLED", note: "combat phase — five step words; `attacks`/`blocks`/`becomes-blocked`/combat damage" },
  "507": { verdict: "MODELLED", note: "beginning of combat — `begin-combat`, an engine verb (301 cards)" },
  "508": { verdict: "MODELLED", note: "declare attackers — `attacks`; 508.4 put onto the battlefield attacking is `enters` with combat: attacking" },
  "509": { verdict: "MODELLED", note: "declare blockers — `blocks`, `becomes-blocked`; no engine verb for either (no card SUPPLIES a block)" },
  "510": { verdict: "MODELLED", note: "combat damage — `combat-damage` engine verb, `combat-damage-step` word; first strike ordering not modelled" },
  "511": { verdict: "MODELLED", note: "end of combat — `end-of-combat`; temporary tokens sacrificed here are `Ability.temporary`" },
  "512": { verdict: "MODELLED", note: "ending phase — `end-step`, `cleanup`" },
  "513": { verdict: "MODELLED", note: "end step — `end-step`, an engine verb; 'the next end step' delayed triggers land here" },
  "514": { verdict: "MODELLED", note: "cleanup — `cleanup`; hand-size discard not modelled as an event (0 cards trigger on it)" },
  "600": { verdict: "N/A", note: "spells, abilities and effects — general" },
  "601": { verdict: "PARTIAL", note: "casting — `cast` emit and word, on-cast abilities; alternative and additional costs are 118's open hole" },
  "602": { verdict: "PARTIAL", note: "activating — `activate` is a word (36 consumers) with no producer: nothing emits an activation", probe: /(when|whenever)[^.]{0,30}\bactivate/i },
  "603": { verdict: "MODELLED", note: "triggered abilities — the engine's spine: trigger words (134), intervening-if ratchet, `reflexive` (603.12c) and `state` (603.8) since 2026-09-09" },
  "605": { verdict: "MODELLED", note: "mana abilities — `add-mana` kind, `tapped-for-mana` word (106.12a); Ability.cost carries the {T}" },
  "606": { verdict: "MODELLED", note: "loyalty abilities — kind `loyalty`, `activate` covers 'whenever you activate a loyalty ability'" },
  "608": { verdict: "PARTIAL", note: "resolving — `resolves` is a word (2 consumers) with no engine verb; fizzling is not modelled" },
  "609": { verdict: "N/A", note: "effects, general — the effect KINDS are 610-615's business" },
  "610": { verdict: "MODELLED", note: "one-shot effects — every action verb is one; the emit/kind tables" },
  "612": { verdict: "OPEN", note: "text-changing effects — 13 cards change text (Mind Bend, Sleight of Mind …); unmodelled and unlikely to matter", probe: /\bchange the text of\b/i },
  "613": { verdict: "OPEN", note: "interaction of continuous effects (layers) — no layer model; the same hole 611 records" },
  "616": { verdict: "N/A", note: "interaction of replacement/prevention effects — follows 614/615, which are OPEN; nothing to model until they are" },
  "803": { verdict: "N/A", note: "attack left/right — not EDH" },
  "804": { verdict: "N/A", note: "deploy creatures — not EDH" },
  "805": { verdict: "N/A", note: "shared team turns — not EDH" },
  "807": { verdict: "N/A", note: "grand melee — not EDH" },
  "808": { verdict: "N/A", note: "team vs team — not EDH" },
  "809": { verdict: "N/A", note: "emperor — not EDH" },
  "810": { verdict: "N/A", note: "two-headed giant — not EDH" },
  "811": { verdict: "N/A", note: "alternating teams — not EDH" },
  "900": { verdict: "N/A", note: "casual variants, general — 903 is the live one" },
  "901": { verdict: "N/A", note: "Planechase — excluded on legality" },
  "902": { verdict: "N/A", note: "Vanguard — excluded on legality" },
  "904": { verdict: "N/A", note: "Archenemy — excluded on legality" },
  "905": { verdict: "N/A", note: "Conspiracy Draft — excluded on legality" },
};
