/** Every artifact, battle, creature, enchantment and land subtype, lowercased.
 *
 *  GENERATED by `gen-vocabulary.ts` from MTGJSON's CardTypes catalogue. Do not edit by hand —
 *  re-run the generator, which is free.
 *
 *  A CLOSED list rather than a head-noun heuristic: `parseSubject` reads free text, and any word it
 *  guesses to be a subtype becomes a filter `edges.ts` matches against another card's type line —
 *  so a wrong guess silently DELETES an edge rather than widening one.
 *
 *  Planeswalker, plane and spell subtypes are deliberately absent from THIS set, and are emitted to
 *  `vocabulary.json` instead. They are real typal identities, but several planeswalker types are
 *  ordinary English words ("will", "comet") and matching them in free text would trade a real edge
 *  for a silent false one. A caller that knows it is looking at a planeswalker can read them there.
 */
export const SUBTYPES: ReadonlySet<string> = new Set([
  "advisor", "aetherborn", "alien", "ally", "angel", "antelope", "ape", "archer",
  "archon", "armadillo", "army", "artificer", "assassin", "assembly-worker", "astartes", "atog",
  "attraction", "aura", "aurochs", "automaton", "avatar", "azra", "background", "badger",
  "balloon", "barbarian", "bard", "basilisk", "bat", "bear", "beast", "beaver",
  "beeble", "beholder", "berserker", "bird", "bison", "blinkmoth", "blood", "boar",
  "bobblehead", "book", "borg", "brainiac", "bringer", "brushwagg", "c'tan", "camarid",
  "camel", "capybara", "caribou", "carrier", "cartouche", "case", "cat", "cave",
  "centaur", "chicken", "child", "chimera", "citizen", "class", "cleric", "cloud",
  "clown", "clue", "cockatrice", "construct", "contraption", "coward", "coyote", "crab",
  "crocodile", "curse", "custodes", "cyberman", "cyclops", "dalek", "dauthi", "demigod",
  "demon", "desert", "deserter", "detective", "devil", "dinosaur", "djinn", "doctor",
  "dog", "dragon", "drake", "dreadnought", "drix", "drone", "druid", "dryad",
  "dwarf", "echidna", "efreet", "egg", "elder", "eldrazi", "elemental", "elephant",
  "elf", "elk", "employee", "equipment", "eternal", "eye", "faerie", "ferret",
  "fish", "flagbearer", "food", "forest", "fortification", "fox", "fractal", "frog",
  "fungus", "gamer", "gamma", "gargoyle", "gate", "germ", "giant", "giraffe",
  "gith", "glimmer", "gnoll", "gnome", "goat", "goblin", "god", "gold",
  "golem", "gorgon", "graveborn", "gremlin", "griffin", "guest", "hag", "halfling",
  "hamster", "harpy", "head", "hedgehog", "hellion", "hero", "hippo", "hippogriff",
  "homarid", "homunculus", "horror", "horse", "human", "hydra", "hyena", "illusion",
  "imp", "incarnation", "incubator", "infinity", "inhuman", "inkling", "inquisitor", "insect",
  "island", "jackal", "jellyfish", "juggernaut", "junk", "kangaroo", "kavu", "kirin",
  "kithkin", "klingon", "knight", "kobold", "kor", "kraken", "kree", "lair",
  "lamia", "lammasu", "leech", "lemur", "leviathan", "lhurgoyf", "licid", "lizard",
  "llama", "lobster", "locus", "manticore", "map", "masticore", "mercenary", "merfolk",
  "metathran", "mine", "minion", "minotaur", "mite", "mole", "monger", "mongoose",
  "monk", "monkey", "moogle", "moonfolk", "mount", "mountain", "mouse", "mutant",
  "myr", "mystic", "naga", "nautilus", "necron", "nephilim", "nightmare", "nightstalker",
  "ninja", "noble", "noggle", "nomad", "nymph", "octopus", "officer", "ogre",
  "ooze", "orb", "orc", "orgg", "otter", "ouphe", "ox", "oyster",
  "pangolin", "peasant", "pegasus", "pentavite", "performer", "pest", "phelddagrif", "phoenix",
  "phyrexian", "pilot", "pincher", "pirate", "plains", "plan", "planet", "plant",
  "platypus", "porcupine", "possum", "power-plant", "powerstone", "praetor", "primarch", "prism",
  "processor", "q", "qu", "rabbit", "raccoon", "ranger", "rat", "rebel",
  "reflection", "reveler", "rhino", "rigger", "robot", "rogue", "role", "room",
  "rukh", "rune", "sable", "saga", "salamander", "samurai", "sand", "saproling",
  "satyr", "scarecrow", "scientist", "scion", "scorpion", "scout", "sculpture", "seal",
  "serf", "serpent", "servo", "shade", "shaman", "shapeshifter", "shard", "shark",
  "sheep", "shi'ar", "shrine", "siege", "siren", "skeleton", "skrull", "skunk",
  "slith", "sliver", "sloth", "slug", "snail", "snake", "soldier", "soltari",
  "sorcerer", "spacecraft", "spawn", "specter", "spellshaper", "sphere", "sphinx", "spider",
  "spike", "spirit", "splinter", "sponge", "spy", "squid", "squirrel", "starfish",
  "stone", "surrakar", "survivor", "swamp", "symbiote", "synth", "teddy", "tentacle",
  "terminus", "tetravite", "thalakos", "thopter", "thrull", "tiefling", "time lord", "tosk",
  "tower", "town", "toy", "treasure", "treefolk", "trilobite", "triskelavite", "troll",
  "turtle", "tyranid", "unicorn", "urza's", "urzan", "utrom", "vampire", "varmint",
  "vedalken", "vehicle", "villain", "volver", "vulcan", "wall", "walrus", "warlock",
  "warrior", "weasel", "weird", "werewolf", "whale", "wizard", "wolf", "wolverine",
  "wombat", "worm", "wraith", "wurm", "yeti", "zombie", "zubera",
]);

/** The LAND subtypes among them. A land subtype means MANA BASE, not typal: a fetchland naming Swamp
 *  is ramp, and a tutor that finds one is a land-fixing card rather than a Swamp-tribal payoff. */
export const LAND_SUBTYPES: ReadonlySet<string> = new Set([
"cave", "cloud", "desert", "forest", "gate", "island", "lair", "locus", "mine", "mountain", "plains", "planet", "power-plant", "sphere", "swamp", "tower", "town", "urza's",
]);
