/** What type a NAMED token is, sourced from the tokens themselves.
 *
 *  "Create two Treasure tokens" parses to `{token: true, subtype: "treasure"}` and no type, because
 *  "token" is not a type word. Matcher's `expandTypes` then falls back to the CARD hierarchy, which
 *  answers `treasure -> artifact+creature` — because Goldhound is an "Artifact Creature — Treasure
 *  Dog". That is the wrong oracle: it answers *could a card with this subtype be a creature*, not
 *  *is this token one*. Big Score, an Instant that creates two Treasures and no creature, fed
 *  Warstorm Surge's "whenever a creature you control enters" on the strength of it.
 *
 *  The right oracle is the `tokens` collection, where a Treasure is flatly
 *  "Token Artifact — Treasure". Generated by `bin/gen-token-types.ts`, free — no key, no spend — and
 *  `--check` fails CI on drift, the same contract `gen-vocabulary` and `gen-hierarchy` already have.
 *
 *  Answering with a UNION across tokens sharing a subtype is deliberate and is not the hierarchy's
 *  mistake repeated: the universe here is tokens only, so "every token printed with this subtype is
 *  one of these types" is a true statement about the thing being created. Where a subtype really is
 *  printed on two token types, both are kept and the matcher ORs them, which is the honest answer. */
import { readFileSync } from "node:fs";
import { CARD_TYPES } from "./subject.js";

const SUPERTYPES = new Set(["legendary", "basic", "snow", "world", "ongoing", "token"]);

/** Build the subtype -> types map from raw token type lines.
 *
 *  Exported for the generator and its test. The lines are messy in ways the card corpus is not:
 *  450 distinct values including bare "Card", "Boss", and double-faced "Card // Token Creature —
 *  Elemental". Each FACE is read independently, and a face naming no subtype or no card type
 *  contributes nothing rather than a guess. */
export function buildTokenTypes(lines: string[]): Record<string, string[]> {
  const out = new Map<string, Set<string>>();
  for (const line of lines) {
    for (const face of line.split("//")) {
      // Em dash is the printed separator; the hyphen fallback is for any hand-entered line.
      const [head, tail] = face.split(/\s+[—-]\s+/);
      if (!tail) continue;
      const types = head.toLowerCase().split(/\s+/)
        .filter((w) => w && !SUPERTYPES.has(w))
        .filter((w) => (CARD_TYPES as readonly string[]).includes(w));
      if (types.length === 0) continue;
      for (const sub of tail.toLowerCase().split(/\s+/).filter(Boolean)) {
        const set = out.get(sub) ?? new Set<string>();
        for (const t of types) set.add(t);
        out.set(sub, set);
      }
    }
  }
  return Object.fromEntries([...out].sort(([a], [b]) => a.localeCompare(b))
    .map(([k, v]) => [k, [...v].sort()]));
}

let cached: Record<string, string[]> | undefined;

/** The bundled map. Read once; the file is generated and checked in. */
export function loadTokenTypes(): Record<string, string[]> {
  cached ??= JSON.parse(readFileSync(new URL("token-types.json", import.meta.url), "utf8")) as
    Record<string, string[]>;
  return cached;
}

/** The type a token with this subtype is, or undefined when the collection does not carry it.
 *  Unknown stays unknown — the same refusal `parseCounter` makes for an unknown counter kind. */
export function tokenTypeFor(subtype: string): string | string[] | undefined {
  const types = loadTokenTypes()[subtype.toLowerCase()];
  if (!types || types.length === 0) return undefined;
  return types.length === 1 ? types[0] : types;
}
